### ISSUE TITLE
Check for Dataset 4

### ISSUE THREAD

**Issue by anglixue** [raymondlouie/ClusterMarkers#17]
Hi,
I am trying to run with dataset 4.
This data is from 10X official website https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_10k_protein_v3

And it is expected to contain ~10K cells with 17 proteins (from TotalSeq-B antibodies). However, I got 6,794,880 cells in the downloaded datasets

```
> dim(seurat_object)
[1]   33538 6794880
```

I wonder if has anyone tested this dataset and could enlighten me why the cell number is inconsistent with the description.

**Comment by raymondlouie** [comment]
See [https://bioinformatics.stackexchange.com/questions/8678/why-do-i-have-10-000-cells-in-the-10x-matrix-produced-by-cellranger](url).

Essentially it's most likely the object prior to filtering by CellRanger

**Comment by anglixue** [comment]
Thanks Ray. I've found that the filtered one before and should've closed this.
