### ISSUE TITLE
Error from findClusterMarkers (v0.1.3)

### ISSUE THREAD

**Issue by HsiaoChiLiao** [raymondlouie/ClusterMarkers#37]
Hi @raymondlouie ,

I am using your latest version (v0.1.3) to re-run all the analyses. The error with `citeFuse` has been fixed but I encountered a different error for some seeds.

```
>  final_out <- readRDS(file = paste0(inpath, file.nam[i]))
>     
>     list_markers = findClusterMarkers(final_out$training_matrix,
+                                       final_out$training_clusters,
+                                       num_markers=15,
+                                       method="all",
+                                       verbose=TRUE)
Using all methods.
Methods used in this analysis: citeFuse, sc2marker, geneBasis, xgBoost

Error in logcounts(sce) <- input_matrix : 
  could not find function "logcounts<-"
```

Please click [here](https://www.dropbox.com/scl/fo/qwc60tl2ld1eib8oenhv2/h?dl=0&rlkey=5l0b9s93g10x1i6iylix3ooei) to access the `final_out` object from the seeds with this issue. Thanks!

**Comment by raymondlouie** [comment]
Thanks @HsiaoChiLiao . This is now fixed, along with other bugs. The problem was the library SingleCellExperiment wasn't loaded, I've now removed the requirement for this in the code (by SingleCellExperiment::logcounts).

**Comment by HsiaoChiLiao** [comment]
Hi @raymondlouie,

Would the other bugs you fixed affect the results from the seeds with no error in the previous version? I was wondering if I can just re-run the seeds with the problem only.

Thanks!

**Comment by raymondlouie** [comment]
Hi @HsiaoChiLiao, I modified the CiteSeq code slightly, but it shouldn't result in major changes to the results. I think it should be fine re-running with the seeds with the problem only.
