### ISSUE TITLE
nrounds in performanceAllMarkers()

### ISSUE THREAD

**Issue by anglixue** [raymondlouie/ClusterMarkers#38]
Hi Ray,

I am trying to explain why the TP in xgboost is often higher in geneBasis.

Do you remember why the `nrounds` is set as 1500 by default? 

I called the original function but found that: 

`performanceAllMarkers()` called `performanceMarkers()`, and then 
`performanceMarkers()` called `xgboostPerformance()`

It seems this parameter is not passed to the final function because `performanceMarkers()` didn't accept this parameter in [line #50](https://github.com/raymondlouie/ClusterMarkers/blob/411fa47b5625c06e3688d9e91c824bbd1929dd93/R/performanceAllMarkers.R#L50).

**Comment by raymondlouie** [comment]
Hi Angli, @HsiaoChiLiao  might be the best person to ask here. I didn't change much from her original xgboost code.

**Comment by HsiaoChiLiao** [comment]
`nrounds` is a parameter (the number of decision trees used in the model) that XGBoost uses for feature selection/prediction. It's not used for calculating TP. 😊
